/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/gateway/wrangler.jsonc --include-runtime=false workers/gateway/worker-configuration.d.ts` (hash: 416280b7829b1ebae760669ef9cd5430)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	IP_RPM_LIMIT: "300";
	PRIVATE_REPOSITORY_RESPONSE: "not_found";
	RATE_LIMITER: DurableObjectNamespace /* SharedRateLimitDurableObject from gitedge-limits */;
	AUTH: Fetcher /* gitedge-auth */;
	FORGE: Fetcher /* gitedge-forge */;
	GIT: Fetcher /* gitedge-git-artifacts */;
	DEPLOY: Fetcher /* gitedge-deploy */;
	ACTIONS: Fetcher /* gitedge-actions */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IP_RPM_LIMIT" | "PRIVATE_REPOSITORY_RESPONSE">> {}
}
