<script lang="ts">
import { computed } from "vue";
import {
  Activity,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowUpRight,
  Bell,
  BookOpen,
  Bot,
  Building2,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  Cloud,
  Compass,
  CodeXml,
  Copy,
  Diff,
  Download,
  Eye,
  ExternalLink,
  File,
  FileText,
  Filter,
  Folder,
  GitBranch,
  GitFork,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  History,
  House,
  Link,
  ListTodo,
  LockKeyhole,
  LogOut,
  Menu,
  MessageCircleMore,
  Plus,
  Search,
  Settings,
  Star,
  ShieldCheck,
  Tag,
  Target,
  Terminal,
  Upload,
  UserRound,
  X,
} from "@lucide/vue";

const icons = {
  activity: Activity,
  agent: Bot,
  alert: AlertCircle,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  bell: Bell,
  book: BookOpen,
  branch: GitBranch,
  check: Check,
  checkCircle: CircleCheck,
  chevron: ChevronDown,
  chevronRight: ChevronRight,
  circle: Circle,
  cloud: Cloud,
  compass: Compass,
  code: CodeXml,
  commit: GitCommitHorizontal,
  copy: Copy,
  diff: Diff,
  discussion: MessageCircleMore,
  download: Download,
  eye: Eye,
  file: File,
  filter: Filter,
  fork: GitFork,
  folder: Folder,
  gear: Settings,
  settings: Settings,
  shield: ShieldCheck,
  github: GitBranch,
  gitMerge: GitMerge,
  home: House,
  issue: CircleDot,
  link: Link,
  lock: LockKeyhole,
  markdown: FileText,
  menu: Menu,
  organization: Building2,
  person: UserRound,
  plus: Plus,
  pr: GitPullRequest,
  repo: CodeXml,
  search: Search,
  signOut: LogOut,
  star: Star,
  tag: Tag,
  target: Target,
  task: ListTodo,
  terminal: Terminal,
  upload: Upload,
  wiki: BookOpen,
  clock: History,
  close: X,
  external: ExternalLink,
  help: CircleHelp,
} as const;
export type IconName = keyof typeof icons;
</script>
<script setup lang="ts">
const props = defineProps<{ name: IconName; size?: number }>();
const icon = computed(() => icons[props.name]);
</script>

<template>
  <component :is="icon" class="icon" :size="size ?? 16" :stroke-width="1.8" aria-hidden="true" />
</template>
