/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/actions/wrangler.jsonc --include-runtime=false workers/actions/worker-configuration.d.ts` (hash: 2a9f4e5efb4844b82c0904147277f36f)
interface __BaseEnv_Env {
	DB: D1Database;
	ACTION_RUNS: DurableObjectNamespace<import("./src/index").ActionRun>;
	GIT: Fetcher /* gitedge-git-artifacts */;
	FORGE: Fetcher /* gitedge-forge */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ActionRun";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
